const DEFAULT_BLACK = "#1C1B1A"
const DEFAULT_WHITE = "#FFFFFF"
const BACKGROUND_GRAY = "#E9EbF0"
const PARAN_NAVY = "#1D2532"
const LIGHT_NAVY = "#657ea8"
const ACTIVATE_GREEN = "#52CE52"
const DEACTIVATE_RED = "#E35353"
const NAV_GRAY = "#767676"

export {PARAN_NAVY, DEFAULT_BLACK, DEFAULT_WHITE, BACKGROUND_GRAY, LIGHT_NAVY, ACTIVATE_GREEN, DEACTIVATE_RED, NAV_GRAY}